'use client';

import { useState } from 'react';

export default function PrivacyPolicy() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <>
      <button
        onClick={() => setIsOpen(true)}
        className="text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200 underline transition-colors"
      >
        Privacy Policy
      </button>

      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          {/* Backdrop */}
          <div 
            className="absolute inset-0 bg-black/50 backdrop-blur-sm animate-fade-in"
            onClick={() => setIsOpen(false)}
          />
          
          {/* Modal */}
          <div className="relative bg-white dark:bg-gray-800 rounded-xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden animate-scale-in">
            {/* Header */}
            <div className="sticky top-0 bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 p-6 flex items-center justify-between z-10">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Privacy Policy</h2>
              <button
                onClick={() => setIsOpen(false)}
                className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
              >
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            {/* Content */}
            <div className="p-6 overflow-y-auto max-h-[calc(90vh-100px)]">
              <div className="prose dark:prose-invert max-w-none">
                <p className="text-sm text-gray-500 dark:text-gray-400 mb-6">
                  <strong>Last Updated:</strong> October 11, 2025
                </p>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">1. Introduction</h3>
                  <p className="text-gray-700 dark:text-gray-300 mb-3">
                    Welcome to QuizApp (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;). We are committed to protecting your privacy and ensuring 
                    the security of your personal information. This Privacy Policy explains how we collect, use, store, 
                    and protect your data when you use our quiz and flashcard application.
                  </p>
                  <p className="text-gray-700 dark:text-gray-300">
                    By using QuizApp, you agree to the collection and use of information in accordance with this policy.
                  </p>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">2. Information We Collect</h3>
                  
                  <h4 className="text-md font-semibold text-gray-800 dark:text-gray-200 mb-2">2.1 Account Information</h4>
                  <p className="text-gray-700 dark:text-gray-300 mb-3">
                    When you create an account using Firebase Authentication, we collect:
                  </p>
                  <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 mb-4 space-y-1">
                    <li>Email address (if using email authentication)</li>
                    <li>Display name and profile photo (if using OAuth providers like Google)</li>
                    <li>Unique user identifier (UID) generated by Firebase</li>
                    <li>Authentication timestamps</li>
                  </ul>

                  <h4 className="text-md font-semibold text-gray-800 dark:text-gray-200 mb-2">2.2 Application Data</h4>
                  <p className="text-gray-700 dark:text-gray-300 mb-3">
                    To provide our services, we store:
                  </p>
                  <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 mb-4 space-y-1">
                    <li>Custom quizzes and flashcard decks you create</li>
                    <li>Quiz attempt history and scores</li>
                    <li>Application settings and preferences</li>
                    <li>Timestamps for data synchronization</li>
                  </ul>

                  <h4 className="text-md font-semibold text-gray-800 dark:text-gray-200 mb-2">2.3 API Keys</h4>
                  <p className="text-gray-700 dark:text-gray-300 mb-3">
                    When you choose to use AI-powered features (quiz and flashcard generation), you may provide:
                  </p>
                  <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 mb-3 space-y-1">
                    <li>Google Gemini API key (optional)</li>
                  </ul>
                  <p className="text-gray-700 dark:text-gray-300">
                    <strong>Important:</strong> API keys are encrypted using AES-256-GCM encryption with a key derived 
                    from your unique user ID before being stored in Firebase. This ensures that even if our database 
                    is compromised, your API keys remain secure and can only be decrypted by you.
                  </p>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">3. How We Use Your Information</h3>
                  <p className="text-gray-700 dark:text-gray-300 mb-3">We use your information to:</p>
                  <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 space-y-1">
                    <li>Provide and maintain our quiz and flashcard services</li>
                    <li>Synchronize your data across multiple devices</li>
                    <li>Enable AI-powered content generation features</li>
                    <li>Personalize your learning experience</li>
                    <li>Track your progress and generate statistics</li>
                    <li>Improve our application and develop new features</li>
                    <li>Communicate important updates about the service</li>
                  </ul>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">4. Data Storage and Security</h3>
                  
                  <h4 className="text-md font-semibold text-gray-800 dark:text-gray-200 mb-2">4.1 Storage Locations</h4>
                  <p className="text-gray-700 dark:text-gray-300 mb-3">Your data is stored in:</p>
                  <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 mb-4 space-y-1">
                    <li><strong>Local Storage:</strong> Browser local storage for quick access and offline functionality</li>
                    <li><strong>Firebase Cloud Firestore:</strong> Google Cloud servers for data synchronization across devices</li>
                    <li><strong>Firebase Authentication:</strong> Secure user identity management</li>
                  </ul>

                  <h4 className="text-md font-semibold text-gray-800 dark:text-gray-200 mb-2">4.2 Security Measures</h4>
                  <p className="text-gray-700 dark:text-gray-300 mb-3">We implement industry-standard security measures:</p>
                  <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 space-y-1">
                    <li><strong>End-to-End Encryption:</strong> API keys are encrypted on your device before transmission</li>
                    <li><strong>AES-256-GCM Encryption:</strong> Military-grade encryption for sensitive data</li>
                    <li><strong>HTTPS/TLS:</strong> All data transmissions are encrypted in transit</li>
                    <li><strong>Firebase Security Rules:</strong> Strict access controls ensure users can only access their own data</li>
                    <li><strong>User-Specific Encryption:</strong> Each user&apos;s API key is encrypted with a unique key derived from their UID</li>
                    <li><strong>No Plaintext Storage:</strong> API keys are never stored in readable format</li>
                  </ul>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">5. Third-Party Services</h3>
                  
                  <h4 className="text-md font-semibold text-gray-800 dark:text-gray-200 mb-2">5.1 Firebase (Google Cloud)</h4>
                  <p className="text-gray-700 dark:text-gray-300 mb-3">
                    We use Google Firebase for authentication and data storage. Firebase&apos;s privacy policy can be found at: 
                    <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener noreferrer" 
                       className="text-blue-600 dark:text-blue-400 hover:underline ml-1">
                      firebase.google.com/support/privacy
                    </a>
                  </p>

                  <h4 className="text-md font-semibold text-gray-800 dark:text-gray-200 mb-2">5.2 Google Gemini API</h4>
                  <p className="text-gray-700 dark:text-gray-300 mb-3">
                    When you use AI-powered features, your content is sent directly from your browser to Google&apos;s Gemini API. 
                    We do not intercept or store this content. Google&apos;s AI privacy policy applies: 
                    <a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noopener noreferrer" 
                       className="text-blue-600 dark:text-blue-400 hover:underline ml-1">
                      ai.google.dev/gemini-api/terms
                    </a>
                  </p>
                  <p className="text-gray-700 dark:text-gray-300">
                    <strong>Note:</strong> Your API key is used to authenticate these requests. We encrypt and store your 
                    API key to make these features more convenient, but Google will process the actual content according 
                    to their policies.
                  </p>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">6. Data Sharing and Disclosure</h3>
                  <p className="text-gray-700 dark:text-gray-300 mb-3">
                    We do not sell, trade, or rent your personal information to third parties. We may share your information only in these circumstances:
                  </p>
                  <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 space-y-1">
                    <li><strong>With your consent:</strong> When you explicitly authorize data sharing</li>
                    <li><strong>Service providers:</strong> With Firebase/Google Cloud for hosting and infrastructure</li>
                    <li><strong>Legal requirements:</strong> When required by law or to protect our legal rights</li>
                    <li><strong>Business transfers:</strong> In case of merger, acquisition, or asset sale (with notice)</li>
                  </ul>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">7. Your Rights and Choices</h3>
                  
                  <h4 className="text-md font-semibold text-gray-800 dark:text-gray-200 mb-2">7.1 Access and Control</h4>
                  <p className="text-gray-700 dark:text-gray-300 mb-3">You have the right to:</p>
                  <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 mb-4 space-y-1">
                    <li>Access all your data through the application interface</li>
                    <li>Edit or delete quizzes, flashcards, and history</li>
                    <li>Update your account information</li>
                    <li>Remove your saved API key at any time</li>
                    <li>Export your data (contact us for assistance)</li>
                  </ul>

                  <h4 className="text-md font-semibold text-gray-800 dark:text-gray-200 mb-2">7.2 Account Deletion</h4>
                  <p className="text-gray-700 dark:text-gray-300">
                    You can delete your account and all associated data at any time. Upon deletion:
                  </p>
                  <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 space-y-1">
                    <li>All quizzes, flashcards, and history will be permanently removed</li>
                    <li>Your encrypted API key will be deleted</li>
                    <li>Your authentication data will be removed from Firebase</li>
                    <li>Deletion is irreversible</li>
                  </ul>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">8. Data Retention</h3>
                  <p className="text-gray-700 dark:text-gray-300">
                    We retain your data for as long as your account is active or as needed to provide services. 
                    If you delete your account, we will delete your data within 30 days, except where we&apos;re required 
                    to retain it for legal or regulatory purposes.
                  </p>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">9. Children&apos;s Privacy</h3>
                  <p className="text-gray-700 dark:text-gray-300">
                    QuizApp is not intended for children under 13 years of age. We do not knowingly collect personal 
                    information from children. If we become aware that we have collected data from a child under 13, 
                    we will take steps to delete such information promptly.
                  </p>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">10. International Data Transfers</h3>
                  <p className="text-gray-700 dark:text-gray-300">
                    Your data may be transferred to and processed on servers located in various countries where Firebase 
                    operates. By using QuizApp, you consent to the transfer of your information to countries outside 
                    your country of residence, which may have different data protection laws.
                  </p>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">11. Cookies and Tracking</h3>
                  <p className="text-gray-700 dark:text-gray-300">
                    We use browser local storage and session storage to maintain your login state and application preferences. 
                    We do not use third-party tracking cookies or analytics services that identify individual users.
                  </p>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">12. Changes to This Privacy Policy</h3>
                  <p className="text-gray-700 dark:text-gray-300">
                    We may update this Privacy Policy from time to time. We will notify you of any changes by posting 
                    the new Privacy Policy on this page and updating the &quot;Last Updated&quot; date. Significant changes will 
                    be highlighted within the application.
                  </p>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">13. Security Breach Notification</h3>
                  <p className="text-gray-700 dark:text-gray-300">
                    In the unlikely event of a data breach that affects your personal information, we will notify you 
                    within 72 hours via email (if provided) and through in-app notification, along with details about 
                    the breach and steps we&apos;re taking to address it.
                  </p>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">14. Contact Us</h3>
                  <p className="text-gray-700 dark:text-gray-300 mb-3">
                    If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:
                  </p>
                  <div className="bg-gray-100 dark:bg-gray-700 p-4 rounded-lg">
                    <p className="text-gray-700 dark:text-gray-300">
                      <strong>QuizApp Support</strong><br />
                      GitHub: <a href="https://github.com/UltimateBoi/QuizApp" target="_blank" rel="noopener noreferrer" 
                                 className="text-blue-600 dark:text-blue-400 hover:underline">
                        github.com/UltimateBoi/QuizApp
                      </a>
                    </p>
                  </div>
                </section>

                <section className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">15. Legal Compliance</h3>
                  <p className="text-gray-700 dark:text-gray-300 mb-3">
                    This Privacy Policy is designed to comply with:
                  </p>
                  <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 space-y-1">
                    <li>General Data Protection Regulation (GDPR) - European Union</li>
                    <li>California Consumer Privacy Act (CCPA) - United States</li>
                    <li>Children&apos;s Online Privacy Protection Act (COPPA) - United States</li>
                    <li>Other applicable international data protection laws</li>
                  </ul>
                </section>

                <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4 mt-8">
                  <p className="text-sm text-blue-800 dark:text-blue-200">
                    <strong>Your Privacy Matters:</strong> We&apos;re committed to transparency and protecting your data. 
                    If you have any questions or concerns about how we handle your information, please don&apos;t hesitate 
                    to reach out. Your trust is important to us.
                  </p>
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="sticky bottom-0 bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 p-4">
              <button
                onClick={() => setIsOpen(false)}
                className="w-full px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
